### PR TITLE
Your new Readme is ready! 🎉

### PR DESCRIPTION
**Pull request by ShruAgarwal**
I have made the suggested changes to your `README.md`. Please have a look and let me know your thoughts! 😊
Also, I would suggest you to :
- Update your *social links* on your personal website.
- Add more about yourself in **About Me** section of this file!

Thanks 🙂

### CODE REVIEW

**Review by Ksound22 — APPROVED** [review]
Thanks, Shruti

**Comment by Ksound22** [comment]
Thank you, Shruti. IT looks good.

**Comment by ShruAgarwal** [comment]
Happy to build your profile! 😄 Thanks for allowing me to do so.🙂

**Comment by Ksound22** [comment]
Thanks a lot for this wonderful contribution

**Pull request merged**
